import { expect, test } from '@playwright/test';
import { loginAs } from './helpers';

test('confirmed field source opens the recording at the selected instant', async ({ page }) => {
    await loginAs(page);
    await page.goto('/opportunities/1/briefing');
    const editor = page.getByRole('region', { name: 'Briefing do evento' });
    await editor.getByRole('button', { name: 'Vincular trecho da reunião' }).first().click();
    const dialog = page.getByRole('dialog');
    await dialog.getByRole('checkbox').check();
    await dialog.getByRole('button', { name: 'Ouvir trecho', exact: true }).click();
    await expect.poll(() => dialog.locator('audio').evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBeGreaterThanOrEqual(8.5);
    await expect.poll(() => dialog.locator('audio').evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBeLessThan(15);
    await dialog.getByRole('button', { name: 'Confirmar origem deste campo' }).click();
    await expect(dialog).not.toBeVisible();
    await page.reload();
    await editor.getByRole('button', { name: 'Consultar origem' }).first().click();
    await expect(dialog.getByText('Cliente de teste: Queremos reunir os parceiros no congresso.').first()).toBeVisible();
    await expect(dialog.getByRole('button', { name: 'Ouvir em 0:08' }).first()).toBeVisible();
});

test('typed event briefing, program and uncertain requirements work through the interface', async ({ page }, testInfo) => {
    await loginAs(page);
    await page.goto('/clients/1');
    await page.getByRole('button', { name: 'Nova oportunidade' }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('Nome do trabalho').fill(`Evento verificado ${testInfo.project.name}`);
    await dialog.getByRole('button', { name: 'Criar oportunidade' }).click();
    await expect(page).toHaveURL(/\/$/);
    await page.getByRole('link', { name: `Evento verificado ${testInfo.project.name} Briefing precisa de revisão` }).click();
    const editor = page.getByRole('region', { name: 'Briefing do evento' });
    await editor.getByRole('combobox', { name: 'Tipo de evento', exact: true }).selectOption('congresso');
    await editor.getByLabel('Início do evento', { exact: true }).fill('2026-10-10T09:00');
    await editor.getByLabel('Término do evento', { exact: true }).fill('2026-10-11T18:00');
    await editor.locator('summary').filter({ hasText: 'Local e público' }).click();
    await editor.getByLabel('Público máximo estimado').fill('150');
    await editor.getByLabel('Perfil do público').fill('Profissionais convidados');
    await editor.getByLabel('Nome e informações do local').fill('Centro de eventos');
    await editor.locator('summary').filter({ hasText: 'Objetivo e proposta' }).click();
    await editor.getByLabel('Objetivo do evento', { exact: true }).fill('Reunir parceiros');
    await editor.getByLabel('Resumo do escopo').fill('Plenária e credenciamento');
    await editor.locator('summary').filter({ hasText: 'Investimento e condições' }).click();
    await editor.getByLabel('Investimento declarado (R$)', { exact: true }).fill('100000.50');
    await editor.locator('summary').filter({ hasText: 'Sucesso, riscos e compromissos' }).click();
    await editor.getByRole('button', { name: 'Adicionar como vamos medir o sucesso' }).click();
    await editor.getByLabel('Indicador', { exact: true }).fill('Participantes');
    await editor.getByLabel('Meta', { exact: true }).fill('150');
    await editor.getByRole('button', { name: 'Salvar briefing do evento', exact: true }).click();
    await expect(editor.getByRole('button', { name: 'Aprovar briefing do evento', exact: true })).toBeEnabled();
    await editor.getByRole('button', { name: 'Novo requisito', exact: true }).click();
    await dialog.getByLabel('Área de produção').selectOption('som');
    await dialog.getByLabel('O que precisa ser entregue').fill('Sonorização da plenária');
    await dialog.getByLabel('O que sabemos sobre este requisito').selectOption('hypothesis');
    await dialog.getByLabel('Origem desta informação').fill('Reunião do cliente');
    await dialog.getByRole('button', { name: 'Salvar requisito' }).click();
    await expect(dialog).not.toBeVisible();
    await editor.getByRole('button', { name: 'Preparar necessidades para cotação' }).click();
    await editor.getByRole('button', { name: 'Confirmar necessidades selecionadas' }).click();
    await expect(editor.getByRole('alert').first()).toContainText('Confirme individualmente');
    await editor.getByLabel('Confirmo que este item pode ser cotado apesar da incerteza').check();
    await editor.getByRole('button', { name: 'Confirmar necessidades selecionadas' }).click();
    await expect(editor.getByText(/Necessidade #\d+ criada/)).toBeVisible();
    await editor.getByRole('button', { name: 'Adicionar bloco', exact: true }).click();
    await dialog.getByLabel('Nome do bloco').fill('Abertura');
    await dialog.getByLabel('Fim do bloco').fill('2026-10-10T11:00');
    await dialog.getByLabel('Origem da programação').fill('Cliente');
    await dialog.getByRole('button', { name: 'Salvar bloco' }).click();
    await expect(dialog).not.toBeVisible();
    await editor.getByRole('button', { name: 'Aprovar briefing do evento', exact: true }).click();
    await expect(editor.getByRole('button', { name: 'Reabrir briefing', exact: true })).toBeVisible();
    await page.reload();
    await expect(editor.getByRole('heading', { name: 'Abertura', exact: true })).toBeVisible();
    await expect(editor.getByLabel('Nome do evento', { exact: true })).toBeDisabled();
    expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
    await page.screenshot({ path: `test-results/event-brief-${testInfo.project.name}.png`, fullPage: true });
});
