import { expect, test } from '@playwright/test';
import { loginAs } from './helpers';

test('payment plan, partial receipt, approved payable and reconciliation persist', async ({page},info)=>{
 await loginAs(page,'finance@example.test');
 await page.goto('/clients/1');
 await page.getByRole('link').filter({hasText:`Financeiro ${info.project.name}`}).click();
 await expect(page).toHaveURL(/\/opportunities\/\d+$/);
 const path=new URL(page.url()).pathname;
 await page.goto(`${path}/finance`);
 await expect(page.getByRole('heading',{name:'Controle financeiro do evento'})).toBeVisible();
 await page.getByRole('button',{name:'Criar plano',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Total do plano (R$)').fill('1000.01');
 await dialog.getByLabel('Porcentagem').fill('50');
 await dialog.getByRole('button',{name:'Adicionar parcela'}).click();
 await dialog.getByLabel('Porcentagem').last().fill('50');
 await dialog.getByLabel('Nome da parcela').last().fill('Saldo');
 await dialog.getByRole('combobox',{name:'Gatilho do vencimento'}).last().selectOption('data_fixa');
 await dialog.getByLabel('Data de vencimento').fill('2026-10-20');
 await dialog.getByRole('button',{name:'Salvar plano',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await page.getByLabel('Evidência do aceite do plano').fill('Condição confirmada pelo cliente de teste');
 await page.getByRole('button',{name:'Registrar aceite e preservar condições'}).click();
 await page.getByRole('button',{name:'Preparar recebíveis'}).click();
 await page.getByRole('button',{name:'Confirmar geração dos recebíveis'}).click();
 const incoming=page.locator('section').filter({has:page.getByRole('heading',{name:'Contas a receber',exact:true})});
 await incoming.getByRole('button',{name:'Registrar baixa'}).first().click();
 await dialog.getByLabel('Valor da baixa (R$)').fill('100');
 await dialog.getByLabel('Comprovante ou evidência').fill('Comprovante sintético conferido');
 await dialog.getByRole('button',{name:'Confirmar baixa',exact:true}).click();
 await expect(incoming.getByText('Baixa parcial')).toBeVisible();
 await expect(incoming.getByText('R$ 400,01',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Novo pagável',exact:true}).click();
 await dialog.getByRole('combobox',{name:'Origem aprovada'}).selectOption({label:'Som de teste · orçamento v1'});
 await dialog.getByLabel('Descrição do pagamento').fill('Fornecedor de som');
 await dialog.getByLabel('Valor a pagar (R$)').fill('100');
 await dialog.getByRole('button',{name:'Registrar para aprovação'}).click();
 await page.getByRole('button',{name:'Aprovar pagamento',exact:true}).click();
 const outgoing=page.locator('section').filter({has:page.getByRole('heading',{name:'Contas a pagar',exact:true})});
 await outgoing.getByRole('button',{name:'Registrar baixa',exact:true}).click();
 await dialog.getByLabel('Comprovante ou evidência').fill('Recibo sintético do fornecedor');
 await dialog.getByRole('button',{name:'Confirmar baixa',exact:true}).click();
 await expect(outgoing.getByText('Quitado',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Conferir som',exact:true}).click();
 await dialog.getByRole('button',{name:'Salvar conferência',exact:true}).click();
 await page.reload();
 await expect(incoming.getByText('Baixa parcial')).toBeVisible();
 await expect(outgoing.getByText('Quitado',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:`test-results/finance-${info.project.name}.png`,fullPage:true});
});
