<?php

use App\Http\Controllers\AiSettingsController;
use App\Http\Controllers\AssistantController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BriefingAudioController;
use App\Http\Controllers\BriefingController;
use App\Http\Controllers\BriefStructureController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\CaseAttachmentController;
use App\Http\Controllers\CaseContextController;
use App\Http\Controllers\CaseJourneyController;
use App\Http\Controllers\CommercialWorkflowController;
use App\Http\Controllers\ContextAudioReviewController;
use App\Http\Controllers\ContextAudioUploadController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DecisionQueueController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentShareController;
use App\Http\Controllers\DocumentsHubController;
use App\Http\Controllers\EventBriefController;
use App\Http\Controllers\EventFinanceController;
use App\Http\Controllers\FeasibilityController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FoundationController;
use App\Http\Controllers\OperationalPagesController;
use App\Http\Controllers\OpportunityController;
use App\Http\Controllers\OpportunityWorkspaceController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\PostEventController;
use App\Http\Controllers\ProductionController;
use App\Http\Controllers\PrototypeController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SupplierQuoteComparisonController;
use App\Http\Controllers\SupplierSourcingController;
use App\Http\Controllers\VenueController;
use App\Models\Opportunity;
use App\Services\BudgetIntake;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'show'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [PasswordResetController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'send'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'edit'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'update'])->middleware('throttle:password-reset')->name('password.update');
});

Route::get('/shared/proposal/{token}', [DocumentShareController::class, 'show'])->name('documents.shared.show');
Route::post('/shared/proposal/{token}/decision', [DocumentShareController::class, 'decide'])->name('documents.shared.decision');

Route::middleware('auth')->group(function (): void {
    Route::get('/assistant/chat', [AssistantController::class, 'chatHistory']);
    Route::post('/assistant/chat', [AssistantController::class, 'chat'])->middleware('throttle:10,1');
    Route::post('/assistant/chat/{turn}/preview', [AssistantController::class, 'editChatPreview'])->whereNumber('turn');
    Route::post('/assistant/interpret', [AssistantController::class, 'interpret'])->middleware('throttle:10,1');
    Route::post('/opportunities/{opportunity}/documents/{document}/review', [DocumentController::class, 'review']);
    Route::get('/opportunities/{opportunity}/documents/{document}/release', [DocumentController::class, 'release']);
    Route::post('/opportunities/{opportunity}/documents/{document}/reopen', [DocumentController::class, 'reopen']);
    Route::post('/opportunities/{opportunity}/documents/{document}/sent', [DocumentController::class, 'sent']);
    Route::post('/opportunities/{opportunity}/documents/{document}/external-signature', [DocumentController::class, 'externalSignature']);
    Route::post('/opportunities/{opportunity}/documents/{document}/share', [DocumentController::class, 'share']);
    Route::post('/opportunities/{opportunity}/documents/{document}/share/{share}/revoke', [DocumentController::class, 'revokeShare'])->whereNumber('share');
    Route::get('/opportunities/{opportunity}/documents/{document}/pdf', [DocumentController::class, 'pdf']);
    Route::get('/assistant/context', [AssistantController::class, 'context']);
    Route::post('/assistant/messages', [AssistantController::class, 'store'])->middleware('throttle:20,1');
    Route::get('/assistant/previews/{preview}', [AssistantController::class, 'show']);
    Route::post('/assistant/previews/{preview}/confirm', [AssistantController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/budget/intake', function (Request $r, Opportunity $opportunity) {
        app(BudgetIntake::class)->import($opportunity, $r->user(), $r->all());

        return back()->with('success', 'Item incluído no rascunho. Revise antes de aprovar.');
    });
    Route::post('/opportunities/{opportunity}/supplier-needs', [SupplierSourcingController::class, 'storeNeed']);
    Route::post('/opportunities/{opportunity}/supplier-needs/{need}/quotes/{quote}/select', [SupplierSourcingController::class, 'selectQuote']);
    Route::get('/settings/ai', [AiSettingsController::class, 'show'])->middleware('can:manage-ai');
    Route::post('/settings/ai', [AiSettingsController::class, 'store'])->middleware('can:manage-ai');
    Route::post('/settings/ai/test', [AiSettingsController::class, 'test'])->middleware(['can:manage-ai', 'throttle:5,1']);
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', DashboardController::class)->name('dashboard');
    Route::get('/projects', [PrototypeController::class, 'index'])->name('projects');
    Route::post('/prototype', [PrototypeController::class, 'store']);
    Route::post('/prototype/{prototype}/actions', [PrototypeController::class, 'action']);
    Route::get('/prototype/{prototype}/documents/{document}/print', [PrototypeController::class, 'print']);
    Route::get('/prototype/{prototype}/{section}', [PrototypeController::class, 'show']);
    Route::post('/opportunities', [OpportunityController::class, 'store'])->name('opportunities.store');
    Route::patch('/opportunities/{opportunity}', [OpportunityController::class, 'update'])->name('opportunities.update');
    Route::get('/opportunities/{opportunity}/edit', [OpportunityController::class, 'edit'])->name('opportunities.edit');
    Route::post('/clients', [FoundationController::class, 'clientStore']);
    Route::get('/clients/{client}/cover', [\App\Http\Controllers\ClientCoverController::class, 'show']);
    Route::post('/clients/{client}/cover', [\App\Http\Controllers\ClientCoverController::class, 'store']);
    Route::get('/clients/{client}', [FoundationController::class, 'clientShow']);
    Route::patch('/clients/{client}', [FoundationController::class, 'clientUpdate']);
    Route::post('/clients/{client}/archive', [FoundationController::class, 'clientArchive']);
    Route::post('/clients/{client}/restore', [FoundationController::class, 'clientRestore']);
    Route::post('/clients/{client}/contacts', [FoundationController::class, 'contactStore']);
    Route::patch('/clients/{client}/contacts/{contact}', [FoundationController::class, 'contactUpdate']);
    Route::post('/clients/{client}/contacts/{contact}/archive', [FoundationController::class, 'contactArchive']);
    Route::post('/clients/{client}/contacts/{contact}/restore', [FoundationController::class, 'contactRestore']);
    Route::post('/team', [FoundationController::class, 'userStore'])->middleware('can:manage-team');
    Route::patch('/team/{user}', [FoundationController::class, 'userUpdate'])->middleware('can:manage-team');
    Route::post('/team/{user}/password', [FoundationController::class, 'userPassword'])->middleware('can:manage-team');
    Route::post('/team/{user}/commercial-authority', [FoundationController::class, 'commercialAuthority'])->middleware('can:manage-team');
    Route::post('/activities', [FoundationController::class, 'activityStore']);
    Route::patch('/activities/{activity}', [FoundationController::class, 'activityUpdate']);
    Route::post('/activities/{activity}/complete', [FoundationController::class, 'activityComplete']);
    Route::post('/activities/{activity}/reopen', [FoundationController::class, 'activityReopen']);
    Route::post('/activities/{activity}/reschedule', [FoundationController::class, 'activityReschedule']);
    Route::post('/activities/{activity}/assign', [FoundationController::class, 'activityAssign']);
    Route::delete('/activities/{activity}', [FoundationController::class, 'activityDestroy']);
    Route::post('/pipeline/bulk-priority', [CommercialWorkflowController::class, 'bulkPriority']);
    Route::post('/pipeline/bulk-priority/undo', [CommercialWorkflowController::class, 'undoBulkPriority']);
    Route::get('/opportunities/{opportunity}', [OpportunityWorkspaceController::class, 'show'])->name('opportunities.show');
    Route::post('/opportunities/{opportunity}/archive', [CommercialWorkflowController::class, 'archive']);
    Route::post('/opportunities/{opportunity}/restore', [CommercialWorkflowController::class, 'restore']);
    Route::post('/opportunities/{opportunity}/qualification', [CommercialWorkflowController::class, 'qualification']);
    Route::post('/opportunities/{opportunity}/commercial-stage', [CommercialWorkflowController::class, 'stage']);
    Route::post('/opportunities/{opportunity}/next-action', [CommercialWorkflowController::class, 'nextAction']);
    Route::post('/opportunities/{opportunity}/prepare', [OpportunityWorkspaceController::class, 'prepare']);
    Route::get('/opportunities/{opportunity}/journey', [CaseJourneyController::class, 'show']);
    Route::post('/opportunities/{opportunity}/journey', [CaseJourneyController::class, 'update']);
    Route::get('/opportunities/{opportunity}/feasibility', [FeasibilityController::class, 'show'])->name('opportunities.feasibility');
    Route::post('/opportunities/{opportunity}/feasibility', [FeasibilityController::class, 'store']);
    Route::post('/opportunities/{opportunity}/feasibility/lifecycle', [FeasibilityController::class, 'lifecycle']);
    Route::post('/opportunities/{opportunity}/feasibility/deliverables/{deliverable}', [FeasibilityController::class, 'updateDeliverable']);
    Route::get('/opportunities/{opportunity}/documents', DocumentsHubController::class)->name('opportunities.documents');
    Route::post('/opportunities/{opportunity}/context', [CaseContextController::class, 'store']);
    Route::post('/opportunities/{opportunity}/context/audio/uploads', [ContextAudioUploadController::class, 'start'])->middleware('throttle:20,1');
    Route::get('/opportunities/{opportunity}/context/audio/uploads/{session}', [ContextAudioUploadController::class, 'show']);
    Route::put('/opportunities/{opportunity}/context/audio/uploads/{session}/chunks/{index}', [ContextAudioUploadController::class, 'chunk'])->whereNumber('index')->middleware('throttle:120,1')->withoutScopedBindings();
    Route::post('/opportunities/{opportunity}/context/audio/uploads/{session}/complete', [ContextAudioUploadController::class, 'complete'])->middleware('throttle:20,1')->withoutScopedBindings();
    Route::get('/opportunities/{opportunity}/context/audio/latest', [ContextAudioReviewController::class, 'latest']);
    Route::get('/opportunities/{opportunity}/context/{entry}/audio', [ContextAudioReviewController::class, 'audio']);
    Route::patch('/opportunities/{opportunity}/context/{entry}/speakers', [ContextAudioReviewController::class, 'update']);
    Route::post('/opportunities/{opportunity}/context/{entry}/process', [ContextAudioReviewController::class, 'process'])->middleware('throttle:10,1');
    Route::get('/opportunities/{opportunity}/context/{entry}', [CaseContextController::class, 'show']);
    Route::post('/opportunities/{opportunity}/context/{entry}/preview/{preview}/confirm', [CaseContextController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/stage', [OpportunityController::class, 'updateStage'])->name('opportunities.stage');
    Route::get('/pipeline', [OperationalPagesController::class, 'pipeline'])->name('pipeline');
    Route::get('/briefings', [OperationalPagesController::class, 'briefings'])->name('briefings');
    Route::get('/agenda', [OperationalPagesController::class, 'agenda'])->name('agenda');
    Route::get('/clients', [OperationalPagesController::class, 'clients'])->name('clients');
    Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers');
    Route::get('/suppliers/duplicates', [SupplierController::class, 'duplicates']);
    Route::post('/suppliers', [SupplierController::class, 'store']);
    Route::get('/suppliers/{supplier}', [SupplierController::class, 'show']);
    Route::post('/suppliers/{supplier}/inquiries', [SupplierController::class, 'inquiry']);
    Route::patch('/suppliers/{supplier}', [SupplierController::class, 'update']);
    Route::post('/suppliers/{supplier}/quotes', [SupplierController::class, 'quote']);
    Route::post('/opportunities/{opportunity}/quote-comparisons', [SupplierQuoteComparisonController::class, 'store'])->name('opportunities.quote-comparisons.store');
    Route::get('/opportunities/{opportunity}/quote-comparisons/{comparison}/export', [SupplierQuoteComparisonController::class, 'export'])->name('opportunities.quote-comparisons.export');
    Route::get('/venues', [VenueController::class, 'index'])->name('venues');
    Route::post('/venues', [VenueController::class, 'store']);
    Route::get('/venues/{venue}', [VenueController::class, 'show'])->name('venues.show');
    Route::patch('/venues/{venue}', [VenueController::class, 'update']);
    Route::get('/history', [OperationalPagesController::class, 'history'])->name('history');
    Route::get('/opportunities/{opportunity}/history', [OperationalPagesController::class, 'history']);
    Route::get('/team', [OperationalPagesController::class, 'team'])->name('team');
    Route::get('/help', [OperationalPagesController::class, 'help'])->name('help');
    Route::get('/search', SearchController::class)->name('search');
    Route::post('/opportunities/{opportunity}/attachments', [CaseAttachmentController::class, 'store']);
    Route::get('/opportunities/{opportunity}/attachments/{attachment}', [CaseAttachmentController::class, 'download']);
    Route::post('/opportunities/{opportunity}/attachments/{attachment}/archive', [CaseAttachmentController::class, 'archive']);
    Route::post('/opportunities/{opportunity}/attachments/{attachment}/restore', [CaseAttachmentController::class, 'restore']);
    Route::post('/opportunities/{opportunity}/blockers', [DecisionQueueController::class, 'store']);
    Route::post('/opportunities/{opportunity}/blockers/{blocker}/resolve', [DecisionQueueController::class, 'resolve']);
    Route::post('/opportunities/{opportunity}/blockers/{blocker}/reopen', [DecisionQueueController::class, 'reopen']);
    Route::get('/opportunities/{opportunity}/finance', [EventFinanceController::class, 'show']);
    Route::post('/opportunities/{opportunity}/finance/plan', [EventFinanceController::class, 'plan']);
    Route::post('/opportunities/{opportunity}/finance/plan/{plan}/accept', [EventFinanceController::class, 'accept']);
    Route::post('/opportunities/{opportunity}/finance/plan/{plan}/preview', [EventFinanceController::class, 'preview']);
    Route::post('/opportunities/{opportunity}/finance/preview/{preview}/confirm', [EventFinanceController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/finance/payables', [EventFinanceController::class, 'payable']);
    Route::post('/opportunities/{opportunity}/finance/payables/{entry}/approve', [EventFinanceController::class, 'approve']);
    Route::post('/opportunities/{opportunity}/finance/{ledger}/{entry}/settle', [EventFinanceController::class, 'settle'])->whereIn('ledger', ['receivables', 'payables']);
    Route::post('/opportunities/{opportunity}/finance/{ledger}/{entry}/cancel', [EventFinanceController::class, 'cancel'])->whereIn('ledger', ['receivables', 'payables']);
    Route::post('/opportunities/{opportunity}/finance/receivables/{entry}/due', [EventFinanceController::class, 'due']);
    Route::post('/opportunities/{opportunity}/finance/costs', [EventFinanceController::class, 'cost']);
    Route::get('/opportunities/{opportunity}/briefing', [BriefingController::class, 'show'])->name('opportunities.briefing');
    Route::patch('/opportunities/{opportunity}/event-brief', [EventBriefController::class, 'update']);
    Route::post('/opportunities/{opportunity}/event-brief/approve', [EventBriefController::class, 'approve']);
    Route::post('/opportunities/{opportunity}/event-brief/reopen', [EventBriefController::class, 'reopen']);
    Route::post('/opportunities/{opportunity}/event-brief/requirements', [BriefStructureController::class, 'requirementStore']);
    Route::patch('/opportunities/{opportunity}/event-brief/requirements/{requirement}', [BriefStructureController::class, 'requirementUpdate']);
    Route::post('/opportunities/{opportunity}/event-brief/needs-preview', [BriefStructureController::class, 'preview']);
    Route::post('/opportunities/{opportunity}/event-brief/needs-preview/{preview}/confirm', [BriefStructureController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/event-brief/program', [BriefStructureController::class, 'programStore']);
    Route::patch('/opportunities/{opportunity}/event-brief/program/{block}', [BriefStructureController::class, 'programUpdate']);
    Route::delete('/opportunities/{opportunity}/event-brief/program/{block}', [BriefStructureController::class, 'programRemove']);
    Route::patch('/opportunities/{opportunity}/event-brief/program-order', [BriefStructureController::class, 'programOrder']);
    Route::post('/opportunities/{opportunity}/event-brief/sources', [BriefStructureController::class, 'sourceStore']);
    Route::patch('/opportunities/{opportunity}/event-brief/context/{entry}', [BriefStructureController::class, 'contextMetadata']);
    Route::post('/opportunities/{opportunity}/briefing/review', [BriefingController::class, 'review']);
    Route::post('/opportunities/{opportunity}/briefing/audio', [BriefingAudioController::class, 'store']);
    Route::get('/opportunities/{opportunity}/briefing/audio/{audio}', [BriefingAudioController::class, 'show']);
    Route::post('/opportunities/{opportunity}/briefing/audio/{audio}/transcribe', [BriefingAudioController::class, 'transcribe']);
    Route::post('/opportunities/{opportunity}/briefing/audio/{audio}/forward', [BriefingAudioController::class, 'forward']);
    Route::patch('/opportunities/{opportunity}/briefing/audio/{audio}', [BriefingAudioController::class, 'update']);
    Route::post('/opportunities/{opportunity}/briefing/messages', [BriefingController::class, 'store'])->name('opportunities.briefing.messages.store');
    Route::post('/opportunities/{opportunity}/budget/items', [BudgetController::class, 'storeItem'])->name('opportunities.budget.items.store');
    Route::patch('/opportunities/{opportunity}/budget/items/{item}', [BudgetController::class, 'updateItem']);
    Route::delete('/opportunities/{opportunity}/budget/items/{item}', [BudgetController::class, 'removeItem']);
    Route::post('/opportunities/{opportunity}/budget/versions', [BudgetController::class, 'duplicate']);
    Route::post('/opportunities/{opportunity}/quotes/{quote}/select', [BudgetController::class, 'selectQuote']);
    Route::post('/opportunities/{opportunity}/budget/approve', [BudgetController::class, 'approve'])->name('opportunities.budget.approve');
    Route::get('/opportunities/{opportunity}/budget', [BudgetController::class, 'show'])->name('opportunities.budget');
    Route::get('/production', [ProductionController::class, 'index'])->name('production.index');
    Route::get('/production/events/{opportunity}', [ProductionController::class, 'show'])->name('production.event');
    Route::get('/production/events/{opportunity}/post-event', [PostEventController::class, 'show'])->name('production.post-event');
    Route::get('/opportunities/{opportunity}/production', [ProductionController::class, 'show'])->name('opportunities.production');
    Route::get('/opportunities/{opportunity}/post-event', [PostEventController::class, 'show'])->name('opportunities.post-event');
    Route::post('/opportunities/{opportunity}/post-event', [PostEventController::class, 'store'])->name('opportunities.post-event.store');
    Route::post('/opportunities/{opportunity}/post-event/reopen', [PostEventController::class, 'reopen'])->name('opportunities.post-event.reopen');
    Route::post('/opportunities/{opportunity}/production/tasks', [ProductionController::class, 'storeTask'])->name('opportunities.production.tasks.store');
    Route::post('/opportunities/{opportunity}/production/checklists', [ProductionController::class, 'storeChecklist'])->name('opportunities.production.checklists.store');
    Route::post('/opportunities/{opportunity}/production/checklists/items/{item}/complete', [ProductionController::class, 'completeChecklistItem'])->name('opportunities.production.checklists.items.complete');
    Route::post('/opportunities/{opportunity}/production/service-orders', [ProductionController::class, 'storeServiceOrder'])->name('opportunities.production.service-orders.store');
    Route::post('/opportunities/{opportunity}/production/service-orders/{order}/issue', [ProductionController::class, 'issueServiceOrder'])->name('opportunities.production.service-orders.issue');
    Route::post('/opportunities/{opportunity}/production/service-orders/{order}/receive', [ProductionController::class, 'receiveServiceOrder'])->name('opportunities.production.service-orders.receive');
    Route::post('/opportunities/{opportunity}/production/technical-validations', [ProductionController::class, 'saveTechnicalValidation'])->name('opportunities.production.technical-validations.store');
    Route::post('/opportunities/{opportunity}/production/technical-validations/{validation}/confirm', [ProductionController::class, 'confirmTechnicalValidation'])->name('opportunities.production.technical-validations.confirm');
    Route::post('/opportunities/{opportunity}/production/prepare', [ProductionController::class, 'prepareScope'])->name('opportunities.production.prepare');
    Route::post('/opportunities/{opportunity}/production/previews/{preview}/confirm', [ProductionController::class, 'confirmScope'])->name('opportunities.production.previews.confirm');
    Route::patch('/production/tasks/{task}', [ProductionController::class, 'updateTask'])->name('production.tasks.update');
    Route::post('/production/tasks/{task}/schedule', [ProductionController::class, 'scheduleTask'])->name('production.tasks.schedule');
    Route::get('/opportunities/{opportunity}/{type}', [DocumentController::class, 'show'])->whereIn('type', ['proposal', 'contract'])->name('opportunities.document');
    Route::post('/opportunities/{opportunity}/{type}', [DocumentController::class, 'update'])->whereIn('type', ['proposal', 'contract'])->name('opportunities.document.update');
    Route::post('/feedback', [FeedbackController::class, 'store'])->name('feedback.store');
});
