<?php

use App\Http\Controllers\AiSettingsController;
use App\Http\Controllers\AssistantController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BriefingAudioController;
use App\Http\Controllers\BriefingController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\CaseContextController;
use App\Http\Controllers\CaseJourneyController;
use App\Http\Controllers\CommercialWorkflowController;
use App\Http\Controllers\ContextAudioReviewController;
use App\Http\Controllers\ContextAudioUploadController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentsHubController;
use App\Http\Controllers\FeasibilityController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FoundationController;
use App\Http\Controllers\OperationalPagesController;
use App\Http\Controllers\OpportunityController;
use App\Http\Controllers\OpportunityWorkspaceController;
use App\Http\Controllers\PostEventController;
use App\Http\Controllers\ProductionController;
use App\Http\Controllers\PrototypeController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SupplierController;
use App\Models\Opportunity;
use App\Services\BudgetIntake;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'show'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login')->name('login.store');
});

Route::middleware('auth')->group(function (): void {
    Route::post('/assistant/interpret', [AssistantController::class, 'interpret'])->middleware('throttle:10,1');
    Route::post('/opportunities/{opportunity}/documents/{document}/review', [DocumentController::class, 'review']);
    Route::post('/opportunities/{opportunity}/documents/{document}/sent', [DocumentController::class, 'sent']);
    Route::get('/opportunities/{opportunity}/documents/{document}/pdf', [DocumentController::class, 'pdf']);
    Route::get('/assistant/context', [AssistantController::class, 'context']);
    Route::post('/assistant/messages', [AssistantController::class, 'store'])->middleware('throttle:20,1');
    Route::get('/assistant/previews/{preview}', [AssistantController::class, 'show']);
    Route::post('/assistant/previews/{preview}/confirm', [AssistantController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/budget/intake', function (Request $r, Opportunity $opportunity) {
        app(BudgetIntake::class)->import($opportunity, $r->user(), $r->all());

        return back()->with('success', 'Item incluído no rascunho. Revise antes de aprovar.');
    });
    Route::get('/settings/ai', [AiSettingsController::class, 'show'])->middleware('can:manage-ai');
    Route::post('/settings/ai', [AiSettingsController::class, 'store'])->middleware('can:manage-ai');
    Route::post('/settings/ai/test', [AiSettingsController::class, 'test'])->middleware(['can:manage-ai', 'throttle:5,1']);
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', DashboardController::class)->name('dashboard');
    Route::get('/projects', [PrototypeController::class, 'index'])->name('projects');
    Route::post('/prototype', [PrototypeController::class, 'store']);
    Route::post('/prototype/{prototype}/actions', [PrototypeController::class, 'action']);
    Route::get('/prototype/{prototype}/documents/{document}/print', [PrototypeController::class, 'print']);
    Route::get('/prototype/{prototype}/{section}', [PrototypeController::class, 'show']);
    Route::post('/opportunities', [OpportunityController::class, 'store'])->name('opportunities.store');
    Route::patch('/opportunities/{opportunity}', [OpportunityController::class, 'update'])->name('opportunities.update');
    Route::get('/opportunities/{opportunity}/edit', [OpportunityController::class, 'edit'])->name('opportunities.edit');
    Route::post('/clients', [FoundationController::class, 'clientStore']);
    Route::get('/clients/{client}', [FoundationController::class, 'clientShow']);
    Route::patch('/clients/{client}', [FoundationController::class, 'clientUpdate']);
    Route::post('/clients/{client}/archive', [FoundationController::class, 'clientArchive']);
    Route::post('/clients/{client}/restore', [FoundationController::class, 'clientRestore']);
    Route::post('/clients/{client}/contacts', [FoundationController::class, 'contactStore']);
    Route::patch('/clients/{client}/contacts/{contact}', [FoundationController::class, 'contactUpdate']);
    Route::post('/clients/{client}/contacts/{contact}/archive', [FoundationController::class, 'contactArchive']);
    Route::post('/clients/{client}/contacts/{contact}/restore', [FoundationController::class, 'contactRestore']);
    Route::post('/team', [FoundationController::class, 'userStore'])->middleware('can:manage-team');
    Route::patch('/team/{user}', [FoundationController::class, 'userUpdate'])->middleware('can:manage-team');
    Route::post('/team/{user}/password', [FoundationController::class, 'userPassword'])->middleware('can:manage-team');
    Route::post('/team/{user}/commercial-authority', [FoundationController::class, 'commercialAuthority'])->middleware('can:manage-team');
    Route::post('/activities', [FoundationController::class, 'activityStore']);
    Route::patch('/activities/{activity}', [FoundationController::class, 'activityUpdate']);
    Route::post('/activities/{activity}/complete', [FoundationController::class, 'activityComplete']);
    Route::post('/activities/{activity}/reopen', [FoundationController::class, 'activityReopen']);
    Route::post('/activities/{activity}/reschedule', [FoundationController::class, 'activityReschedule']);
    Route::post('/activities/{activity}/assign', [FoundationController::class, 'activityAssign']);
    Route::delete('/activities/{activity}', [FoundationController::class, 'activityDestroy']);
    Route::get('/opportunities/{opportunity}', [OpportunityWorkspaceController::class, 'show'])->name('opportunities.show');
    Route::post('/opportunities/{opportunity}/archive', [CommercialWorkflowController::class, 'archive']);
    Route::post('/opportunities/{opportunity}/restore', [CommercialWorkflowController::class, 'restore']);
    Route::post('/opportunities/{opportunity}/qualification', [CommercialWorkflowController::class, 'qualification']);
    Route::post('/opportunities/{opportunity}/commercial-stage', [CommercialWorkflowController::class, 'stage']);
    Route::post('/opportunities/{opportunity}/next-action', [CommercialWorkflowController::class, 'nextAction']);
    Route::post('/opportunities/{opportunity}/prepare', [OpportunityWorkspaceController::class, 'prepare']);
    Route::get('/opportunities/{opportunity}/journey', [CaseJourneyController::class, 'show']);
    Route::post('/opportunities/{opportunity}/journey', [CaseJourneyController::class, 'update']);
    Route::get('/opportunities/{opportunity}/feasibility', [FeasibilityController::class, 'show'])->name('opportunities.feasibility');
    Route::post('/opportunities/{opportunity}/feasibility', [FeasibilityController::class, 'store']);
    Route::post('/opportunities/{opportunity}/feasibility/lifecycle', [FeasibilityController::class, 'lifecycle']);
    Route::post('/opportunities/{opportunity}/feasibility/deliverables/{deliverable}', [FeasibilityController::class, 'updateDeliverable']);
    Route::get('/opportunities/{opportunity}/documents', DocumentsHubController::class)->name('opportunities.documents');
    Route::post('/opportunities/{opportunity}/context', [CaseContextController::class, 'store']);
    Route::post('/opportunities/{opportunity}/context/audio/uploads', [ContextAudioUploadController::class, 'start'])->middleware('throttle:20,1');
    Route::put('/opportunities/{opportunity}/context/audio/uploads/{session}/chunks/{index}', [ContextAudioUploadController::class, 'chunk'])->whereNumber('index')->middleware('throttle:120,1')->withoutScopedBindings();
    Route::post('/opportunities/{opportunity}/context/audio/uploads/{session}/complete', [ContextAudioUploadController::class, 'complete'])->middleware('throttle:20,1')->withoutScopedBindings();
    Route::get('/opportunities/{opportunity}/context/audio/latest', [ContextAudioReviewController::class, 'latest']);
    Route::get('/opportunities/{opportunity}/context/{entry}/audio', [ContextAudioReviewController::class, 'audio']);
    Route::patch('/opportunities/{opportunity}/context/{entry}/speakers', [ContextAudioReviewController::class, 'update']);
    Route::post('/opportunities/{opportunity}/context/{entry}/process', [ContextAudioReviewController::class, 'process'])->middleware('throttle:10,1');
    Route::get('/opportunities/{opportunity}/context/{entry}', [CaseContextController::class, 'show']);
    Route::post('/opportunities/{opportunity}/context/{entry}/preview/{preview}/confirm', [CaseContextController::class, 'confirm']);
    Route::post('/opportunities/{opportunity}/stage', [OpportunityController::class, 'updateStage'])->name('opportunities.stage');
    Route::get('/pipeline', [OperationalPagesController::class, 'pipeline'])->name('pipeline');
    Route::get('/briefings', [OperationalPagesController::class, 'briefings'])->name('briefings');
    Route::get('/agenda', [OperationalPagesController::class, 'agenda'])->name('agenda');
    Route::get('/clients', [OperationalPagesController::class, 'clients'])->name('clients');
    Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers');
    Route::get('/suppliers/duplicates', [SupplierController::class, 'duplicates']);
    Route::post('/suppliers', [SupplierController::class, 'store']);
    Route::get('/suppliers/{supplier}', [SupplierController::class, 'show']);
    Route::post('/suppliers/{supplier}/inquiries', [SupplierController::class, 'inquiry']);
    Route::patch('/suppliers/{supplier}', [SupplierController::class, 'update']);
    Route::post('/suppliers/{supplier}/quotes', [SupplierController::class, 'quote']);
    Route::get('/history', [OperationalPagesController::class, 'history'])->name('history');
    Route::get('/opportunities/{opportunity}/history', [OperationalPagesController::class, 'history']);
    Route::get('/team', [OperationalPagesController::class, 'team'])->name('team');
    Route::get('/help', [OperationalPagesController::class, 'help'])->name('help');
    Route::get('/search', SearchController::class)->name('search');
    Route::get('/opportunities/{opportunity}/briefing', [BriefingController::class, 'show'])->name('opportunities.briefing');
    Route::post('/opportunities/{opportunity}/briefing/review', [BriefingController::class, 'review']);
    Route::post('/opportunities/{opportunity}/briefing/audio', [BriefingAudioController::class, 'store']);
    Route::get('/opportunities/{opportunity}/briefing/audio/{audio}', [BriefingAudioController::class, 'show']);
    Route::post('/opportunities/{opportunity}/briefing/audio/{audio}/transcribe', [BriefingAudioController::class, 'transcribe']);
    Route::post('/opportunities/{opportunity}/briefing/audio/{audio}/forward', [BriefingAudioController::class, 'forward']);
    Route::patch('/opportunities/{opportunity}/briefing/audio/{audio}', [BriefingAudioController::class, 'update']);
    Route::post('/opportunities/{opportunity}/briefing/messages', [BriefingController::class, 'store'])->name('opportunities.briefing.messages.store');
    Route::post('/opportunities/{opportunity}/budget/items', [BudgetController::class, 'storeItem'])->name('opportunities.budget.items.store');
    Route::patch('/opportunities/{opportunity}/budget/items/{item}', [BudgetController::class, 'updateItem']);
    Route::delete('/opportunities/{opportunity}/budget/items/{item}', [BudgetController::class, 'removeItem']);
    Route::post('/opportunities/{opportunity}/budget/versions', [BudgetController::class, 'duplicate']);
    Route::post('/opportunities/{opportunity}/budget/approve', [BudgetController::class, 'approve'])->name('opportunities.budget.approve');
    Route::get('/opportunities/{opportunity}/budget', [BudgetController::class, 'show'])->name('opportunities.budget');
    Route::get('/opportunities/{opportunity}/production', [ProductionController::class, 'show'])->name('opportunities.production');
    Route::get('/opportunities/{opportunity}/post-event', [PostEventController::class, 'show'])->name('opportunities.post-event');
    Route::post('/opportunities/{opportunity}/post-event', [PostEventController::class, 'store'])->name('opportunities.post-event.store');
    Route::post('/opportunities/{opportunity}/production/tasks', [ProductionController::class, 'storeTask'])->name('opportunities.production.tasks.store');
    Route::patch('/production/tasks/{task}', [ProductionController::class, 'updateTask'])->name('production.tasks.update');
    Route::get('/opportunities/{opportunity}/{type}', [DocumentController::class, 'show'])->whereIn('type', ['proposal', 'contract'])->name('opportunities.document');
    Route::post('/opportunities/{opportunity}/{type}', [DocumentController::class, 'update'])->whereIn('type', ['proposal', 'contract'])->name('opportunities.document.update');
    Route::post('/feedback', [FeedbackController::class, 'store'])->name('feedback.store');
});
