import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { AppLayout } from '../layout';
import { GlassSurface } from '../components/GlassSurface';
import { Drawer, FilterBar, Field } from '../components/FormControls';
import { FormErrors } from '../components/FormErrors';
import { CalendarDays, Check, Plus } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
import { Surface } from '../components/ui/Surface';
type Option = { id: number; name?: string; title?: string };
type Activity = { id: number; title: string; description: string | null; user_id: number | null; opportunity_id: number | null; status: string; priority: string; type: string; due_at: string | null; opportunity?: { title: string } | null; assignee?: { name: string } | null };
type Task = { id: number; title: string; status: string; priority: string; due_date: string | null; opportunity_id: number; opportunity?: { title: string } };
type Props = { activities: Activity[]; users: Option[]; opportunities: Option[]; tasks: Task[]; events: { id: number; title: string; event_date: string }[] };
const eventDateLabel = (value: string) => {
    const parts = value.match(/^(\d{2})\/(\d{2})\/(\d{4})/) || value.match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!parts) return value;
    const iso = value.includes('-');
    const day = iso ? Number(parts[3]) : Number(parts[1]);
    const month = iso ? Number(parts[2]) : Number(parts[2]);
    return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(2026, month - 1, day));
};
function ActivityForm({ activity, users, opportunities }: { activity?: Activity; users: Option[]; opportunities: Option[] }) {
    const form = useForm({ title: activity?.title || '', description: activity?.description || '', user_id: activity?.user_id?.toString() || '', opportunity_id: activity?.opportunity_id?.toString() || '', status: activity?.status || 'todo', priority: activity?.priority || 'normal', type: activity?.type || 'task', due_at: activity?.due_at?.slice(0, 16) || '' });
    return <form className="form-grid" onSubmit={e => { e.preventDefault(); activity ? form.patch(`/activities/${activity.id}`) : form.post('/activities', { onSuccess: () => form.reset() }); }}><label>Atividade<input required value={form.data.title} onChange={e => form.setData('title', e.target.value)} /></label><label>Descrição<textarea value={form.data.description} onChange={e => form.setData('description', e.target.value)} /></label><label>Responsável<select value={form.data.user_id} onChange={e => form.setData('user_id', e.target.value)}><option value="">Sem responsável</option>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Caso relacionado<select value={form.data.opportunity_id} onChange={e => form.setData('opportunity_id', e.target.value)}><option value="">Tarefa interna (sem evento)</option>{opportunities.map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Prazo<input type="datetime-local" value={form.data.due_at} onChange={e => form.setData('due_at', e.target.value)} /></label><label>Tipo<select value={form.data.type} onChange={e => form.setData('type', e.target.value)}><option value="task">Tarefa</option><option value="meeting">Reunião</option><option value="follow_up">Follow-up</option></select></label><label>Prioridade<select value={form.data.priority} onChange={e => form.setData('priority', e.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label>Status<select value={form.data.status} onChange={e => form.setData('status', e.target.value)}><option value="todo">A fazer</option><option value="in_progress">Em andamento</option><option value="done">Concluída</option><option value="cancelled">Cancelada</option></select></label><FormErrors errors={form.errors} /><button className="button button-primary" disabled={form.processing}>{activity ? 'Salvar atividade' : 'Criar atividade'}</button>{activity && activity.status !== 'cancelled' && <button className="button button-subtle" type="button" onClick={() => { if (confirm('Cancelar esta atividade? O histórico será preservado.')) router.delete(`/activities/${activity.id}`); }}>Cancelar atividade</button>}</form>;
}
export default function Agenda({ activities, users, opportunities, tasks, events }: Props) {
    const [owner, setOwner] = useState(''); const [status, setStatus] = useState('pending'); const [creating, setCreating] = useState(false);
    const rows = activities.filter(a => (!owner || String(a.user_id) === owner) && (status === 'all' || !['done', 'cancelled'].includes(a.status)));
    const visibleTasks = tasks.filter(t => status === 'all' || t.status !== 'done');
    return <AppLayout><Head title="Tarefas e agenda" />
        <PageHeader eyebrow="Fila da equipe" title="Tarefas e agenda" description="Trabalho interno, compromissos comerciais e produção em um lugar." primaryAction={<button className="button button-primary" type="button" onClick={() => setCreating(true)}><Plus size={16}/> Nova atividade</button>} />
        <Surface className="agenda-filter-surface" padding="sm"><FilterBar><Field label="Responsável"><select value={owner} onChange={e => setOwner(e.target.value)}><option value="">Todos</option>{users.map(u => <option value={u.id} key={u.id}>{u.name}</option>)}</select></Field><Field label="Exibir"><select value={status} onChange={e => setStatus(e.target.value)}><option value="pending">Pendentes</option><option value="all">Todo histórico</option></select></Field></FilterBar></Surface>
        <section className="agenda-workspace"><div className="agenda-workspace__main"><GlassSurface><div className="panel-heading"><div><span className="eyebrow">PRÓXIMOS MOVIMENTOS</span><h2>Atividades e follow-ups</h2></div><span className="status-pill violet">{rows.length}</span></div>{rows.map(a => <details key={a.id}><summary className="client-row"><div><strong>{a.title}</strong><small>{a.assignee?.name || 'Sem responsável'} · {a.opportunity?.title || 'Interna'} · {a.due_at ? new Date(a.due_at).toLocaleString('pt-BR') : 'Sem prazo'}</small></div><span className="status-pill gray">{a.status}</span></summary><ActivityForm activity={a} users={users} opportunities={opportunities} /></details>)}{!rows.length && <p className="inline-empty">Nenhuma atividade neste filtro.</p>}</GlassSurface><GlassSurface><div className="panel-heading"><div><span className="eyebrow">CHECKPOINTS</span><h2>Produção</h2></div><span className="status-pill gray">{visibleTasks.length}</span></div><div className="agenda-task-list">{visibleTasks.map(t => <div className={`agenda-task-row ${t.status}`} key={t.id}><button className="task-check" type="button" aria-label={`${t.status === 'done' ? 'Reabrir' : 'Concluir'} ${t.title}`} onClick={() => router.patch(`/production/tasks/${t.id}`, { status: t.status === 'done' ? 'todo' : 'done' }, { preserveScroll: true })}><Check size={13}/></button><Link href={`/opportunities/${t.opportunity_id}/production`}><strong>{t.title}</strong><small>{t.opportunity?.title} · {t.due_date?.slice(0, 10) || 'Sem prazo'}</small></Link></div>)}</div>{!visibleTasks.length && <p className="inline-empty">Nenhum checkpoint de produção neste filtro.</p>}</GlassSurface></div><GlassSurface className="event-dates-card"><div className="panel-heading"><div><span className="eyebrow">CALENDÁRIO</span><h2>Datas de evento</h2></div><CalendarDays size={18}/></div>{events.map(e => <Link className="event-date-row" href={`/opportunities/${e.id}`} key={e.id}><span><strong>{eventDateLabel(e.event_date)}</strong></span><div><strong>{e.title}</strong><small>Abra o caso para revisar a preparação.</small></div></Link>)}{!events.length && <p className="inline-empty">Nenhuma data de evento definida.</p>}</GlassSurface></section>
        <Drawer title="Nova atividade" open={creating} onClose={() => setCreating(false)}><p className="drawer-intro">Crie a próxima ação e conecte-a ao responsável e ao caso quando necessário.</p><ActivityForm users={users} opportunities={opportunities} /></Drawer>
    </AppLayout>;
}
