import { Head, useForm } from '@inertiajs/react';
import { AppLayout } from '../layout';

export const aiLabels: Record<string, string> = { manual: 'Operação manual', demo: 'Demonstração · sem envio externo', ready: 'Pronta para processar', missing_key: 'Falta cadastrar a chave', policy_pending: 'Política de uso pendente', limits_pending: 'Configure tarifas e limites', limit_reached: 'Limite mensal atingido' };
type Settings = { mode: string; status: string; has_key: boolean; credential_source: string; policy_approved: boolean; monthly_usd: number; processing_usd: number; input_price: number; output_price: number; retention_days: number; used_usd: number; model: string };
export default function AiSettings({ settings, attempts }: { settings: Settings; attempts: {id:number; action:string; status:string; reserved_micros:number; charged_micros:number|null; created_at:string}[] }) {
    const form = useForm({ mode: settings.mode, credential_source: settings.credential_source, api_key: '', remove_key: false, password: '', monthly_usd: String(settings.monthly_usd), processing_usd: String(settings.processing_usd), input_price: String(settings.input_price), output_price: String(settings.output_price), policy_approved: settings.policy_approved, retention_days: settings.retention_days });
    const test = useForm({ password: '' });
    return <AppLayout><Head title="Inteligência artificial" /><header className="topbar"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Inteligência artificial</h1><p>Você controla o motor, os dados e quanto pode gastar.</p></div></header>
        <section className="assistance-banner"><div><strong>{aiLabels[settings.status]}</strong><p>{settings.model} · {settings.has_key ? 'Credencial cadastrada' : 'Sem credencial'} · Limite comprometido neste mês: US$ {settings.used_usd.toFixed(4)}</p></div></section>
        <div className="assistance-grid"><form className="glass-surface assistance-panel form-grid" autoComplete="off" onSubmit={e => {e.preventDefault(); form.post('/settings/ai', {preserveScroll:true, onFinish:()=>form.reset('api_key','password')});}}>
            <h2>Funcionamento e segurança</h2>
            <label>Modo<select value={form.data.mode} onChange={e=>form.setData('mode',e.target.value)}><option value="manual">Manual — sem chamadas externas</option><option value="demo">Demonstração — respostas simuladas</option><option value="openai">OpenAI — processamento pago</option></select></label>
            <label>Origem da chave<select value={form.data.credential_source} onChange={e=>form.setData('credential_source',e.target.value)}><option value="settings">Cadastrada nesta administração</option><option value="environment">Ambiente privado do servidor</option></select></label>
            <label>Nova chave OpenAI<input type="password" autoComplete="new-password" value={form.data.api_key} onChange={e=>form.setData('api_key',e.target.value)} placeholder="Deixe vazio para manter a atual" /></label>
            <label className="assistance-check"><input type="checkbox" checked={form.data.remove_key} onChange={e=>form.setData('remove_key',e.target.checked)} /> Remover chave ativa e desabilitar envio externo</label>
            <label className="assistance-check"><input type="checkbox" checked={form.data.policy_approved} onChange={e=>form.setData('policy_approved',e.target.checked)} /> Confirmo que a equipe validou quais dados podem ser enviados à OpenAI.</label>
            <h2>Orçamento de processamento</h2><p>Valores em dólares. Tarifas por milhão de tokens: confirme as tarifas da sua conta antes de habilitar. Zero mantém chamadas pagas bloqueadas.</p>
            {([['monthly_usd','Limite mensal (US$)'],['processing_usd','Limite por processamento (US$)'],['input_price','Tarifa de entrada (US$ / milhão)'],['output_price','Tarifa de saída (US$ / milhão)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.000001" value={form.data[key]} onChange={e=>form.setData(key,e.target.value)} /></label>)}
            <label>Retenção de áudio (dias)<input type="number" min="1" max="365" value={form.data.retention_days} onChange={e=>form.setData('retention_days',Number(e.target.value))} /></label>
            <label>Confirme sua senha<input type="password" autoComplete="current-password" required value={form.data.password} onChange={e=>form.setData('password',e.target.value)} /></label>
            {Object.values(form.errors).map((error,i)=><p className="assistance-error" role="alert" key={i}>{error}</p>)}
            <button className="button button-primary" disabled={form.processing}>Salvar configurações</button>
        </form><aside className="glass-surface assistance-panel"><h2>Teste seguro</h2><p>Usa apenas um cenário fictício. O custo é contabilizado. Salve as configurações primeiro.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();test.post('/settings/ai/test',{preserveScroll:true,onFinish:()=>test.reset()});}}><label>Sua senha<input type="password" autoComplete="current-password" value={test.data.password} onChange={e=>test.setData('password',e.target.value)} /></label>{Object.values(test.errors).map((error,i)=><p role="alert" key={i}>{error}</p>)}<button className="button button-subtle" disabled={test.processing||settings.status!=='ready'}>{test.processing?'Testando…':'Testar conexão'}</button></form><h2>Últimos processamentos</h2><p>Reservas incluem tentativas sem confirmação de cobrança; não representam a fatura oficial.</p>{attempts.length===0?<p>Nenhuma chamada paga registrada.</p>:attempts.map(a=><article className="assistance-record" key={a.id}><strong>{a.action} · {a.status}</strong><p>US$ {((a.charged_micros??a.reserved_micros)/1000000).toFixed(6)} · {a.created_at}</p></article>)}</aside></div>
    </AppLayout>;
}
