import { Head, useForm } from '@inertiajs/react';
import { ArrowRight, CheckCircle2, Sparkles } from 'lucide-react';
import { FormEvent } from 'react';

export default function Login() {
    const { data, setData, post, processing, errors } = useForm({ email: 'test@example.com', password: 'password', remember: true });
    function submit(event: FormEvent) { event.preventDefault(); post('/login'); }
    return <><Head title="Entrar" /><main className="login-shell login-shell-v2"><section className="login-context"><div className="login-context__brand"><span>PR</span><strong>Padrão RD</strong></div><div className="login-context__copy"><span className="eyebrow">PADRÃO RD OS</span><h1>Uma operação inteira, em contexto.</h1><p>Do briefing à entrega, a equipe encontra a próxima decisão sem reconstruir o trabalho.</p><ul><li><CheckCircle2 size={15} /> Próxima ação sempre visível</li><li><CheckCircle2 size={15} /> IA prepara, pessoas decidem</li><li><CheckCircle2 size={15} /> Histórico preservado</li></ul></div><div className="login-art-footer"><Sparkles size={15} /> Inteligência assistiva · revisão humana</div></section><section className="login-card login-card-v2"><div className="login-heading"><span className="eyebrow">BEM-VINDO DE VOLTA</span><h2>Entrar no workspace</h2><p>Use seu acesso interno para continuar a operação.</p></div><form className="form-grid" onSubmit={submit}><label>E-mail<input type="email" value={data.email} onChange={(event) => setData('email', event.target.value)} autoComplete="email" />{errors.email && <small className="field-error">{errors.email}</small>}</label><label>Senha<input type="password" value={data.password} onChange={(event) => setData('password', event.target.value)} autoComplete="current-password" />{errors.password && <small className="field-error">{errors.password}</small>}</label><button className="button button-primary login-submit" type="submit" disabled={processing}>{processing ? 'Entrando…' : 'Entrar no sistema'}<ArrowRight size={16} /></button></form><small className="demo-credential">Demonstração local: <strong>test@example.com</strong> · <strong>password</strong></small></section></main></>;
}
