import { Head, router, useForm } from '@inertiajs/react';
import { CalendarDays, Check, CircleAlert, FileCheck2, ListChecks, Plus, RefreshCw, ShieldCheck, UserRound } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { AppLayout } from '../layout';
import { GlassSurface } from '../components/GlassSurface';
import { CasePageHeader } from '../components/CasePageHeader';
import { SegmentedControl } from '../components/ui/SegmentedControl';

type Task = { id: number; title: string; description?: string | null; status: string; priority: string; phase?: string | null; dueDate?: string | null; dependencyId?: number | null; dependencyTitle?: string | null; blockedReason?: string | null; technicalValidationId?: number | null; technicalValidation?: { id: number; reference: string; status: string } | null; revision?: number };
type Validation = { id: number; reference: string; measurements?: Record<string, string> | null; evidence?: string | null; supplierName?: string | null; status: string; revision: number; confirmationEvidence?: string | null };
type ScopePreview = { id: number; source?: { budget_id?: number; budget_version?: number } | null; items: { description: string; category?: string; quantity?: string | number; unit?: string | null }[]; status: string; result?: { task_ids?: number[]; count?: number } | null } | null;
type Props = { opportunity: { id: number; title: string; clientName: string; eventDate?: string | null }; tasks: Task[]; validations: Validation[]; scopePreview: ScopePreview };

const labels: Record<string, string> = { todo: 'A fazer', in_progress: 'Em andamento', done: 'Concluída', blocked: 'Bloqueada' };
const phaseLabels: Record<string, string> = { preparation: 'Preparação', setup: 'Montagem', event: 'Evento', teardown: 'Desmontagem' };

export default function Production({ opportunity, tasks, validations, scopePreview }: Props) {
    const [view, setView] = useState<'list' | 'timeline' | 'calendar'>('list');
    const [confirmingValidation, setConfirmingValidation] = useState<number | null>(null);
    const taskForm = useForm({ title: '', description: '', phase: 'preparation', priority: 'normal', due_date: '', dependency_id: '', technical_validation_id: '' });
    const validationForm = useForm({ reference: '', measurements: '', evidence: '', supplier_name: '' });
    const confirmationForm = useForm({ evidence: '', revision: 0 });

    function submitTask(event: FormEvent) {
        event.preventDefault();
        taskForm.post(`/opportunities/${opportunity.id}/production/tasks`, { preserveScroll: true, onSuccess: () => taskForm.reset() });
    }

    function submitValidation(event: FormEvent) {
        event.preventDefault();
        validationForm.transform((data) => ({ ...data, measurements: data.measurements ? Object.fromEntries(data.measurements.split('\n').map((line) => line.split(':').map((part) => part.trim())).filter((parts) => parts.length === 2)) : undefined }));
        validationForm.post(`/opportunities/${opportunity.id}/production/technical-validations`, { preserveScroll: true, onSuccess: () => validationForm.reset() });
    }

    function confirmValidation(event: FormEvent, validation: Validation) {
        event.preventDefault();
        confirmationForm.transform((data) => ({ ...data, revision: validation.revision }));
        confirmationForm.post(`/opportunities/${opportunity.id}/production/technical-validations/${validation.id}/confirm`, { preserveScroll: true, onSuccess: () => { confirmationForm.reset(); setConfirmingValidation(null); } });
    }

    return <AppLayout><Head title={`Produção · ${opportunity.title}`} /><CasePageHeader id={opportunity.id} eyebrow="Produção em movimento" title="Do plano à execução" client={opportunity.clientName} status={`evento em ${opportunity.eventDate || 'data a definir'}`} actions={<span className="status-pill green"><Check size={12} /> {tasks.filter((task) => task.status === 'done').length}/{tasks.length} concluídas</span>} />
        <SegmentedControl value={view} onChange={setView} label="Visualização da produção" segments={[{ value: 'list', label: 'Lista' }, { value: 'timeline', label: 'Linha do tempo' }, { value: 'calendar', label: 'Agenda' }]} />
        <section className={`production-grid production-grid--${view}`}><GlassSurface className="tasks-panel"><div className="panel-heading"><div><span className="eyebrow">{view === 'list' ? 'CHECKLIST OPERACIONAL' : view === 'timeline' ? 'MARCOS E DEPENDÊNCIAS' : 'PRAZOS DO EVENTO'}</span><h2>{view === 'list' ? 'Tarefas do evento' : view === 'timeline' ? 'Linha do tempo' : 'Agenda de produção'}</h2></div><ListChecks size={17} className="muted-icon" /></div>{tasks.length === 0 ? <div className="empty-state"><ListChecks size={25} /><h3>A produção começa aqui.</h3><p>Converta o escopo aprovado em uma prévia ou crie a primeira tarefa manualmente.</p></div> : <div className="task-list">{tasks.map((task) => <div className={`task-row ${task.status}`} key={task.id}><button className="task-check" type="button" aria-label={`${task.status === 'done' ? 'Reabrir' : 'Concluir'} ${task.title}`} onClick={() => router.patch(`/production/tasks/${task.id}`, { status: task.status === 'done' ? 'todo' : 'done' }, { preserveScroll: true })}><Check size={13} /></button><div className="task-copy"><strong>{task.title}</strong><small>{phaseLabels[task.phase || 'preparation']} · {task.description || 'Sem descrição'} · {task.dueDate ? `prazo ${task.dueDate}` : 'sem prazo'}</small>{task.dependencyTitle && <small>Depende de: {task.dependencyTitle}</small>}{task.technicalValidation && <small>Validação técnica: {task.technicalValidation.reference} · {task.technicalValidation.status === 'confirmed' ? 'reconfirmada' : 'pendente'}</small>}{task.blockedReason && <small className="task-blocked-reason">Bloqueio: {task.blockedReason}</small>}</div><span className={`status-pill ${task.priority === 'high' ? 'amber' : task.status === 'done' ? 'green' : task.status === 'blocked' ? 'red' : 'gray'}`}>{task.priority === 'high' ? 'Prioridade alta' : labels[task.status]}</span><UserRound size={14} className="muted-icon" /></div>)}</div>}</GlassSurface>
            <GlassSurface className="task-form-card"><div className="panel-heading"><div><span className="eyebrow">NOVO MARCO</span><h2>Adicionar tarefa</h2></div><Plus size={17} className="muted-icon" /></div><form className="form-grid compact-form" onSubmit={submitTask}><label>Título<input value={taskForm.data.title} onChange={(event) => taskForm.setData('title', event.target.value)} placeholder="Ex.: confirmar fornecedor final" required /></label><label>Descrição<textarea rows={3} value={taskForm.data.description} onChange={(event) => taskForm.setData('description', event.target.value)} placeholder="Contexto para quem vai executar" /></label><div className="two-fields"><label>Fase<select value={taskForm.data.phase} onChange={(event) => taskForm.setData('phase', event.target.value)}><option value="preparation">Preparação</option><option value="setup">Montagem</option><option value="event">Evento</option><option value="teardown">Desmontagem</option></select></label><label>Prioridade<select value={taskForm.data.priority} onChange={(event) => taskForm.setData('priority', event.target.value)}><option value="normal">Normal</option><option value="high">Alta</option><option value="low">Baixa</option></select></label></div><div className="two-fields"><label>Prazo<input type="date" value={taskForm.data.due_date} onChange={(event) => taskForm.setData('due_date', event.target.value)} /></label><label>Depende de<select value={taskForm.data.dependency_id} onChange={(event) => taskForm.setData('dependency_id', event.target.value)}><option value="">Nenhuma</option>{tasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select></label></div>{validations.length > 0 && <label>Validação técnica relacionada<select value={taskForm.data.technical_validation_id} onChange={(event) => taskForm.setData('technical_validation_id', event.target.value)}><option value="">Nenhuma</option>{validations.map((validation) => <option key={validation.id} value={validation.id}>{validation.reference}</option>)}</select></label>}<button className="button button-primary" type="submit" disabled={taskForm.processing}><Plus size={15} /> Criar tarefa</button></form><div className="production-note"><CircleAlert size={14} /><span>Dependências e reconfirmações técnicas bloqueiam uma liberação prematura. O histórico mantém cada decisão.</span></div></GlassSurface></section>

        <section className="production-support-grid"><GlassSurface><div className="panel-heading"><div><span className="eyebrow">ESCOPO CONTRATADO</span><h2>Preparar tarefas</h2></div><FileCheck2 size={18} className="muted-icon" /></div><p>Use o orçamento aprovado como ponto de partida. A conversão cria uma prévia editável e só grava tarefas depois da confirmação.</p>{scopePreview ? <><div className="assistance-record"><strong>{scopePreview.items.length} item(ns) preparados</strong><small>{scopePreview.status === 'confirmed' ? 'Prévia confirmada · tarefas preservadas' : 'Aguardando confirmação humana'}</small></div>{scopePreview.status !== 'confirmed' && <button className="button button-primary" type="button" onClick={() => router.post(`/opportunities/${opportunity.id}/production/previews/${scopePreview.id}/confirm`, {}, { preserveScroll: true })}><Check size={15} /> Confirmar tarefas</button>}</> : <button className="button button-subtle" type="button" onClick={() => router.post(`/opportunities/${opportunity.id}/production/prepare`, {}, { preserveScroll: true })}><RefreshCw size={15} /> Preparar prévia do escopo</button>}</GlassSurface>
            <GlassSurface><div className="panel-heading"><div><span className="eyebrow">VALIDAÇÃO TÉCNICA</span><h2>Visita e reconfirmação</h2></div><ShieldCheck size={18} className="muted-icon" /></div><p>Registre medidas, desenhos e evidências. Qualquer alteração invalida a confirmação anterior.</p><form className="form-grid compact-form" onSubmit={submitValidation}><label>Referência<input required value={validationForm.data.reference} onChange={(event) => validationForm.setData('reference', event.target.value)} placeholder="Ex.: Planta do palco" /></label><label>Medidas (uma por linha)<textarea rows={3} value={validationForm.data.measurements} onChange={(event) => validationForm.setData('measurements', event.target.value)} placeholder="largura: 8m\nprofundidade: 4m" /></label><label>Fornecedor relacionado<input value={validationForm.data.supplier_name} onChange={(event) => validationForm.setData('supplier_name', event.target.value)} placeholder="Nome para reconfirmar" /></label><label>Evidência da visita<textarea rows={2} value={validationForm.data.evidence} onChange={(event) => validationForm.setData('evidence', event.target.value)} placeholder="Link, documento ou observação verificável" /></label><button className="button button-subtle" type="submit" disabled={validationForm.processing}><Plus size={15} /> Salvar validação</button></form>{validations.length > 0 && <div className="validation-list">{validations.map((validation) => <article className="assistance-record" key={validation.id}><div><strong>{validation.reference}</strong><small>{validation.supplierName || 'Fornecedor não informado'} · {validation.status === 'confirmed' ? 'Reconfirmada' : 'Pendente'}</small>{validation.confirmationEvidence && <small>Evidência: {validation.confirmationEvidence}</small>}</div>{validation.status !== 'confirmed' && (confirmingValidation === validation.id ? <form className="inline-form" onSubmit={(event) => confirmValidation(event, validation)}><input required value={confirmationForm.data.evidence} onChange={(event) => confirmationForm.setData('evidence', event.target.value)} placeholder="Evidência da reconfirmação" /><button className="button button-primary" type="submit" disabled={confirmationForm.processing}>Confirmar</button></form> : <button className="button button-subtle" type="button" onClick={() => { confirmationForm.setData('revision', validation.revision); setConfirmingValidation(validation.id); }}>Reconfirmar</button>)}</article>)}</div>}</GlassSurface></section>
        <section className="milestone-strip"><div><CalendarDays size={16} /><span>Próximo marco</span><strong>{opportunity.eventDate || 'Defina a data do evento'}</strong></div><div><Check size={16} /><span>Modo de validação</span><strong>Checklist manual com histórico</strong></div></section></AppLayout>;
}
