import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import { AppLayout } from '../layout';
import { GlassSurface } from '../components/GlassSurface';
type Props = { cases: { id: number; title: string; owner: string; revision: number; viability: string; management: string; outcome: string | null; next: string }[]; opportunities: { id: number; title: string; client: string; owner: string | null; stage: string; next: string | null }[] };
export default function Projects({ cases, opportunities }: Props) {
    const [creating, setCreating] = useState(false);
    return <AppLayout><Head title="Projetos e visão da operação" /><header className="topbar"><div><span className="eyebrow">UMA OPERAÇÃO CONECTADA</span><h1>Do contexto à entrega.</h1><p>Casos da equipe e um laboratório separado para experimentar toda a jornada.</p></div><button className="button button-primary" disabled={creating} onClick={() => router.post('/prototype', {}, { onStart: () => setCreating(true), onFinish: () => setCreating(false) })}>{creating ? 'Preparando…' : '+ Experimentar Conferência Horizonte'}</button></header>
        <GlassSurface className="prototype-intro"><div><span className="status-pill violet">Laboratório · dados fictícios</span><h2>Visualize o sistema completo</h2><p>Explore briefing, Viabilidade, cotações, orçamento, proposta, validação técnica e pós-evento. Os testes não alteram os casos da equipe nem enviam dados para terceiros.</p></div><div className="prototype-route"><span>Comercial</span><span>→ Viabilidade</span><span>→ Gestão opcional</span><span>→ Memória</span></div></GlassSurface>
        <h2 className="prototype-section-title">Seus cenários de demonstração</h2><section className="prototype-card-grid">{cases.map(record => <Link className="prototype-project" key={record.id} href={'/prototype/' + record.id + '/overview'}><span className="eyebrow">DEMO-{record.id} · v{record.revision}</span><h3>{record.title}</h3><p>{record.owner}</p><span className="status-pill violet">{record.outcome ? 'Cenário encerrado' : 'Demonstração persistente'}</span><p>{record.next}</p><strong>Continuar teste →</strong></Link>)}{!cases.length && <p className="inline-empty">Crie o primeiro cenário pelo botão acima. Você poderá repetir os testes sem apagar os anteriores.</p>}</section>
        <h2 className="prototype-section-title">Casos existentes da equipe</h2><section className="prototype-card-grid">{opportunities.map(record => <Link className="prototype-project" key={record.id} href={'/opportunities/' + record.id}><span className="eyebrow">{record.stage}</span><h3>{record.title}</h3><p>{record.client} · {record.owner || 'Responsável a definir'}</p><p>{record.next || 'Defina a próxima ação'}</p><strong>Abrir workspace →</strong></Link>)}</section></AppLayout>;
}
