import { Link } from '@inertiajs/react';
import { useState } from 'react';
import { Drawer, Field } from './FormControls';

export type AssistantContext = { opportunity_id: string; supplier_id: string };
export type ActionPreview = { id: number; mode: string; context: { case_title?: string; supplier_name?: string }; actions: { kind: string; data: Record<string, string> }[] };
export type ActionResult = { demo: boolean; message: string; links: { label: string; href: string }[] };
const definitions: Record<string, { label: string; fields: Record<string,string> }> = {
 'supplier.create': { label: 'Cadastrar fornecedor', fields: { name:'Nome',service:'Serviço',email:'E-mail',phone:'Telefone',notes:'Observações' } },
 'inquiry.create': { label: 'Solicitar cotação (registro interno)', fields: { service:'Serviço',notes:'Observações' } },
 'quote.create': { label: 'Registrar cotação recebida', fields: { service:'Serviço',unit_cost:'Preço em reais (sem separador de milhar)',price_basis:'Base: unit ou total',quantity:'Quantidade coberta',unit:'Unidade',valid_until:'Validade (AAAA-MM-DD)',conditions:'Condições' } },
 'task.create': { label: 'Criar tarefa', fields: { title:'Título',description:'Descrição',due_at:'Prazo (AAAA-MM-DD)',priority:'Prioridade: low, normal ou high' } },
};
async function api(path:string, data?:unknown) {
 const response=await fetch(path,{method:data?'POST':'GET',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||''},...(data?{body:JSON.stringify(data)}:{})});
 const body=await response.json(); if(!response.ok)throw new Error(body.errors?Object.values(body.errors).flat().join(' '):'Não foi possível concluir. Seu texto foi preservado.');return body;
}
export function AssistantPanel({path,mode}:{path:string;mode:string}) {
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[kind,setKind]=useState('supplier.create'),[data,setData]=useState<Record<string,string>>({}),[context,setContext]=useState<AssistantContext>({opportunity_id:path.match(/opportunities\/(\d+)/)?.[1]||new URLSearchParams(location.search).get('opportunity_id')||'',supplier_id:path.match(/suppliers\/(\d+)/)?.[1]||''});
 const [options,setOptions]=useState<{opportunities:{id:number;title:string}[];suppliers:{id:number;name:string}[]}>({opportunities:[],suppliers:[]});
 const [questions,setQuestions]=useState<string[]>([]);
 const [preview,setPreview]=useState<ActionPreview|null>(null),[result,setResult]=useState<ActionResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function show(){setOpen(true);try{setOptions(await api('/assistant/context'));}catch(e){setError((e as Error).message);}}
 async function run(confirm=false){setBusy(true);setError('');try{if(confirm&&preview){setResult(await api(`/assistant/previews/${preview.id}/confirm`,{}));}else setPreview(await api('/assistant/messages',{message,...context,actions:[{kind,data}]}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function interpret(){setBusy(true);setError('');try{const r=await api('/assistant/interpret',{message,kind,...context});setData(r.data);setQuestions(r.questions);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function extract(){const fields:Record<string,string>={};for(const [key,label] of Object.entries(definitions[kind].fields)){const line=message.split('\n').find(line=>line.toLocaleLowerCase('pt-BR').startsWith(label.split(' (')[0].toLocaleLowerCase('pt-BR')+':'));if(line)fields[key]=line.slice(line.indexOf(':')+1).trim();}if(kind==='task.create')fields.description=message;else fields.notes=message;setData(fields);setPreview(null);setResult(null);}
 return <><button type="button" className="button assistant-trigger" onClick={show}>✦ Assistente</button><Drawer title="Assistente contextual" open={open} onClose={()=>setOpen(false)}><p className="status-pill">{mode==='demo'?'Demonstração · não grava na operação':mode==='openai'?'OpenAI · rascunhos sob revisão':'Assistência manual · sem chamada de IA'}</p><p>Cole os dados, confira os campos e veja a prévia. {mode==='openai'?'Use Interpretar com IA para preparar os campos; o texto não será enviado sem esse clique.':'No modo manual, o preenchimento automático usa somente linhas identificadas como Nome: e Serviço:.'}</p>{error&&<p role="alert" className="form-error">{error}</p>}
 {result?<section aria-live="polite"><h3>{result.message}</h3>{result.links.map((link,i)=><p key={i}><Link href={link.href}>{link.label} →</Link></p>)}<button className="button button-subtle" onClick={()=>{setResult(null);setPreview(null);setData({});setMessage('');}}>Novo pedido</button></section>:preview?<section><h3>Confira antes de confirmar</h3><p>Caso: {preview.context.case_title||'Sem vínculo'} · Fornecedor: {preview.context.supplier_name||'Sem vínculo'}</p>{preview.actions.map((action,i)=><div key={i}><strong>{definitions[action.kind]?.label}</strong><dl>{Object.entries(action.data).filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{definitions[action.kind]?.fields[k]||k}</dt><dd>{v}</dd></div>)}</dl></div>)}<p>Nenhuma aprovação, contratação ou envio externo será realizado.</p><div className="rd-form-actions"><button className="button button-subtle" disabled={busy} onClick={()=>setPreview(null)}>Editar prévia</button><button className="button button-primary" disabled={busy} onClick={()=>run(true)}>{busy?'Confirmando…':preview.mode==='demo'?'Confirmar simulação':'Confirmar alterações'}</button></div></section>:<div className="form-grid"><Field label="Caso"><select value={context.opportunity_id} onChange={e=>setContext({...context,opportunity_id:e.target.value})}><option value="">Sem caso selecionado</option>{options.opportunities.map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select></Field><Field label="Fornecedor"><select value={context.supplier_id} onChange={e=>setContext({...context,supplier_id:e.target.value})}><option value="">Sem fornecedor selecionado</option>{options.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="O que preparar?"><select value={kind} onChange={e=>{setKind(e.target.value);setData({});}}>{Object.entries(definitions).map(([key,d])=><option value={key} key={key}>{d.label}</option>)}</select></Field><Field label="Mensagem de origem"><textarea rows={5} value={message} onChange={e=>setMessage(e.target.value)} placeholder={'Cole os dados. Para preencher automaticamente, use uma informação por linha:\nNome: Fornecedor exemplo\nServiço: Iluminação'} /></Field>{mode==='openai'&&<button className="button button-primary" disabled={busy||!message.trim()} onClick={interpret}>{busy?'Interpretando…':'Interpretar com IA'}</button>}{questions.map((q,i)=><p role="status" key={i}>{q}</p>)}<button className="button button-subtle" onClick={extract} disabled={!message.trim()}>Preencher campos identificados</button>{Object.entries(definitions[kind].fields).map(([key,label])=><Field key={key} label={label}><input value={data[key]||''} onChange={e=>setData({...data,[key]:e.target.value})}/></Field>)}<button className="button button-primary" disabled={busy||!message.trim()} onClick={()=>run()}>{busy?'Preparando…':'Ver prévia das alterações'}</button></div>}</Drawer></>;
}
