<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $portal['title'] }} · Padrão RD</title>
<style>body{margin:0;background:#f4f1f7;color:#302b39;font:15px/1.6 system-ui,sans-serif}main{max-width:900px;margin:40px auto;padding:0 22px 70px}header,section{background:#ffffffd9;border:1px solid #e3dbe9;border-radius:24px;padding:30px;margin:20px 0}header{background:linear-gradient(120deg,#faf6ed,#e7ddef)}.brand{letter-spacing:.18em;font-size:12px;color:#66547e}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.2}h1{font-size:44px}h2{font-size:28px}small{color:#6e627b}label{display:block;margin:12px 0}input,textarea,select{display:block;box-sizing:border-box;width:100%;border:1px solid #d7ccdf;padding:12px;border-radius:10px;background:white;font:inherit}button{border:0;border-radius:12px;background:#675087;color:white;padding:12px 20px;font:inherit;cursor:pointer}.notice{padding:15px;background:#e7e0f0;border-radius:12px}.error{background:#fae8e8;padding:12px;border-radius:12px}article{border-top:1px solid #ddd2e5;padding-top:20px;margin-top:20px}.copy{white-space:pre-wrap}li{margin:12px 0}a{color:#654a86}@media(max-width:500px){header,section{padding:22px}h1{font-size:34px}}</style></head><body><main>
<div class="brand">PADRÃO RD / SEU PROJETO</div><header><small>{{ $portal['client'] }}</small><h1>{{ $portal['title'] }}</h1><p class="copy">{{ $portal['message'] }}</p>@if($portal['event_date'])<p>Evento previsto para {{ $portal['event_date'] }}</p>@endif<small>Visão publicada pela equipe. Link válido até {{ \Carbon\Carbon::parse($expires)->format('d/m/Y') }}.</small></header>
@if(session('success'))<p class="notice" role="status">{{ session('success') }}</p>@endif
@if($errors->any())<div class="error" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section><h2>Onde estamos</h2><ol>@foreach($portal['milestones'] as $milestone)<li>{{ $milestone }}</li>@endforeach</ol></section>
@foreach($portal['proposals'] as $proposal)<section><small>PROPOSTA · VERSÃO {{ $proposal['version'] }}</small><h2>{{ $proposal['title'] }}</h2>@foreach($proposal['sections'] as $key=>$text)<h3>{{ ['objective'=>'Objetivo','scope'=>'Escopo','inclusions'=>'O que está incluído','exclusions'=>'O que está fora do escopo','conditions'=>'Condições'][$key] ?? $key }}</h3><p class="copy">{{ is_string($text)?$text:'' }}</p>@endforeach @if(is_numeric($proposal['total_cents']))<p>Valor da proposta: R$ {{ number_format($proposal['total_cents']/100,2,',','.') }}</p>@endif<small>Consulta da versão publicada. Aceite comercial e assinatura seguem pelo canal acordado com a equipe.</small></section>@endforeach
@if(count($portal['deliverables']))<section><h2>Entregas para sua revisão</h2><p>Seu retorno vale para a entrega descrita nesta publicação.</p>@foreach($portal['deliverables'] as $item)<article><h3>{{ $item['title'] }}</h3>@if(isset($responses[$item['key']]))<p class="notice">{{ $responses[$item['key']]->decision==='approved'?'Entrega aprovada':'Ajustes solicitados' }} · {{ $responses[$item['key']]->name }}</p><p>{{ $responses[$item['key']]->message }}</p>@else<form action="/client-portal/{{ $token }}/response" method="post">@csrf<input type="hidden" name="item_key" value="{{ $item['key'] }}"><label>Seu nome<input name="name" required maxlength="160" autocomplete="name"></label><label>Seu retorno<select name="decision"><option value="changes_requested">Solicitar ajustes</option><option value="approved">Aprovar esta entrega</option></select></label><label>Observações<textarea name="message" maxlength="3000" rows="3"></textarea></label><button>Registrar retorno</button></form>@endif</article>@endforeach</section>@endif
<section><h2>Envie seus materiais</h2><p>PDF, JPG ou PNG, até {{ $uploadLimitMb }} MB por arquivo. Os arquivos ficam disponíveis apenas para a equipe responsável.</p><form action="/client-portal/{{ $token }}/upload" method="post" enctype="multipart/form-data">@csrf<label>Seu nome<input name="name" required maxlength="160"></label><label>Arquivo<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required></label><button>Enviar arquivo</button></form></section><small>Padrão RD · Um projeto conectado, do início à entrega.</small>
</main></body></html>
